version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    env_file: ./services/postgres/.env
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - '4080:8080'
    depends_on:
      - 'postgres'
    restart: always
    env_file: ./services/hasura/.env
  hasura-backend-plus:
    image: nhost/hasura-backend-plus:v2.3.0
    ports:
      - '4000:3000'
    restart: always
    env_file: ./services/backend-plus/.env
    volumes:
      - ./services/backend-plus/custom:/app/custom
  minio:
    image: minio/minio
    restart: always
    env_file: ./services/minio/.env
    entrypoint: sh
    command: "-c 'mkdir -p /export/hasura-backend-plus && /usr/bin/minio server /export'"
    volumes:
      - 'minio_data:/data'
  mailhog:
    image: mailhog/mailhog
    ports:
      - 4025:8025 # web ui
volumes:
  db_data:
  minio_data:
