version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - '8088:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: '$HASURA_GRAPHQL_ADMIN_SECRET'
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-backend-plus:3000/auth/jwks"}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
  hasura-backend-plus:
    image: nhost/hasura-backend-plus:v2.3.0
    ports:
      - '3002:3000'
    restart: always
    environment:
      SERVER_URL: http://localhost:3001
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: '$HASURA_GRAPHQL_ADMIN_SECRET'
      JWT_ALGORITHM: RS256
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: hasura-backend-plus
      S3_ACCESS_KEY_ID: minio_access_key
      S3_SECRET_ACCESS_KEY: '${S3_SECRET_ACCESS_KEY:?S3_SECRET_ACCESS_KEY}'
      AUTO_MIGRATE: 'true'
      REGISTRATION_CUSTOM_FIELDS: 'display_name'
      # ANONYMOUS_USERS_ENABLE: "true"
      # DEFAULT_ANONYMOUS_ROLE: "anonymous"
      LOST_PASSWORD_ENABLE: 'true'
      CHANGE_EMAIL_ENABLE: 'true'
      EMAILS_ENABLE: 'true'
      SMTP_HOST: 'mailhog'
      SMTP_PORT: '1025'
      SMTP_PASS: 'password'
      SMTP_USER: 'user'
      SMTP_SECURE: 'false'
      SMTP_SENDER: 'hbp@hbp.com'
    volumes:
      - ./apps/backend-plus/custom:/app/custom
  minio:
    image: minio/minio
    restart: always
    environment:
      S3_BUCKET: hasura-backend-plus
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: '${S3_SECRET_ACCESS_KEY:?S3_SECRET_ACCESS_KEY}' ## min 8 character
    entrypoint: sh
    command: "-c 'mkdir -p /export/hasura-backend-plus && /usr/bin/minio server /export'"
    volumes:
      - 'minio_data:/data'
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
volumes:
  db_data:
  minio_data:
