version: "3.6"
services:
  app:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
    links:
      - graphql-engine
      - hasura-backend-plus
