version: "3.6"
services:
  app:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ${HOME}/.ssh:/.ssh
      - .:/workspace:cached
    command: sleep infinity
    links:
      - graphql-engine
      - hasura-backend-plus
